version: '3.8'

services:
  bot:
    build: .
    container_name: vseznayka_bot
    restart: unless-stopped
    volumes:
      - ./data:/data  # Монтируем локальную папку data
      - ./database.json:/data/database.json  # Монтируем конкретно твой файл
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_DIR=/data
      - DATABASE_FILE=/data/database.json



