version: '3.8'

services:
  bot:
    build: .
    container_name: vseznayka_bot
    restart: unless-stopped
    volumes:
      - railway_data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_DIR=/data
      - DATABASE_FILE=/data/database.json

volumes:
  railway_data:


